stages:
    - build
    - build_docker
    - push_image

build:
    stage: build
    image: node:lts-alpine
    script:
        - "rm package-lock.json"
        - "npm install"
        - "npm run build"
    tags: 
        - docker        
    except:
        - master 

build_docker: 
    stage: build_docker
    script: 
         - "docker build -t vuejs-test ."
    tags:
        - shell
    only:
        - master    


push_image:
    stage: push_image
    script: 
        - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD"
        - "docker tag vuejs-test temirgasimov/vuejs-test:v1"
        - "docker push temirgasimov/vuejs-test:v1"
    tags: 
        - shell
    only:
        - master                 
