// Travis’e hangi dil ile yazdığınızı belirtmelisiniz
language: node_js
// Aynı zamanda Travis’e kullandığınız dilin versiyonunu belirtmelisiniz
node_js:
  - "stable"

before_script:
  - npm install
script:
  - npm run build  
deploy:
  // Deploy işlemi için kullandığınız platformun ismi
  provider: heroku
  // https://dashboard.heroku.com/account adresinden aldığınız API_KEY
  api_key:
    secure: API_KEY
  // Heroku projesinin ismi
  app: test-aa-1
  on:
    // Github reponuzun ismi
    repo: TestVue